<?php

/**
 * Basesolicitud
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $departamento_id
 * @property integer $sf_guard_user_id
 * @property boolean $aprobada
 * @property boolean $predespachada
 * @property boolean $despachada
 * @property boolean $recibida
 * @property departamento $departamento
 * @property sfGuardUser $User
 * @property Doctrine_Collection $detalle_solicitud
 * 
 * @method integer             getId()                Returns the current record's "id" value
 * @method integer             getDepartamentoId()    Returns the current record's "departamento_id" value
 * @method integer             getSfGuardUserId()     Returns the current record's "sf_guard_user_id" value
 * @method boolean             getAprobada()          Returns the current record's "aprobada" value
 * @method boolean             getPredespachada()     Returns the current record's "predespachada" value
 * @method boolean             getDespachada()        Returns the current record's "despachada" value
 * @method boolean             getRecibida()          Returns the current record's "recibida" value
 * @method departamento        getDepartamento()      Returns the current record's "departamento" value
 * @method sfGuardUser         getUser()              Returns the current record's "User" value
 * @method Doctrine_Collection getDetalleSolicitud()  Returns the current record's "detalle_solicitud" collection
 * @method solicitud           setId()                Sets the current record's "id" value
 * @method solicitud           setDepartamentoId()    Sets the current record's "departamento_id" value
 * @method solicitud           setSfGuardUserId()     Sets the current record's "sf_guard_user_id" value
 * @method solicitud           setAprobada()          Sets the current record's "aprobada" value
 * @method solicitud           setPredespachada()     Sets the current record's "predespachada" value
 * @method solicitud           setDespachada()        Sets the current record's "despachada" value
 * @method solicitud           setRecibida()          Sets the current record's "recibida" value
 * @method solicitud           setDepartamento()      Sets the current record's "departamento" value
 * @method solicitud           setUser()              Sets the current record's "User" value
 * @method solicitud           setDetalleSolicitud()  Sets the current record's "detalle_solicitud" collection
 * 
 * @package    saremo
 * @subpackage model
 * @author     UAH
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class Basesolicitud extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('solicitud');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('departamento_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('sf_guard_user_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('aprobada', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('predespachada', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('despachada', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('recibida', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('departamento', array(
             'local' => 'departamento_id',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser as User', array(
             'local' => 'sf_guard_user_id',
             'foreign' => 'id'));

        $this->hasMany('detalle_solicitud', array(
             'local' => 'id',
             'foreign' => 'solicitud_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}