<?php

/**
 * Basearticulo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $descripcion
 * @property integer $categoria_id
 * @property integer $marca_id
 * @property date $fecha_vencimiento
 * @property categoria $categoria
 * @property marca $marca
 * @property Doctrine_Collection $detalle_solicitud
 * @property Doctrine_Collection $inventario
 * 
 * @method integer             getId()                Returns the current record's "id" value
 * @method string              getDescripcion()       Returns the current record's "descripcion" value
 * @method integer             getCategoriaId()       Returns the current record's "categoria_id" value
 * @method integer             getMarcaId()           Returns the current record's "marca_id" value
 * @method date                getFechaVencimiento()  Returns the current record's "fecha_vencimiento" value
 * @method categoria           getCategoria()         Returns the current record's "categoria" value
 * @method marca               getMarca()             Returns the current record's "marca" value
 * @method Doctrine_Collection getDetalleSolicitud()  Returns the current record's "detalle_solicitud" collection
 * @method Doctrine_Collection getInventario()        Returns the current record's "inventario" collection
 * @method articulo            setId()                Sets the current record's "id" value
 * @method articulo            setDescripcion()       Sets the current record's "descripcion" value
 * @method articulo            setCategoriaId()       Sets the current record's "categoria_id" value
 * @method articulo            setMarcaId()           Sets the current record's "marca_id" value
 * @method articulo            setFechaVencimiento()  Sets the current record's "fecha_vencimiento" value
 * @method articulo            setCategoria()         Sets the current record's "categoria" value
 * @method articulo            setMarca()             Sets the current record's "marca" value
 * @method articulo            setDetalleSolicitud()  Sets the current record's "detalle_solicitud" collection
 * @method articulo            setInventario()        Sets the current record's "inventario" collection
 * 
 * @package    saremo
 * @subpackage model
 * @author     UAH
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class Basearticulo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('articulo');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('descripcion', 'string', 80, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 80,
             ));
        $this->hasColumn('categoria_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('marca_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('fecha_vencimiento', 'date', null, array(
             'type' => 'date',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('categoria', array(
             'local' => 'categoria_id',
             'foreign' => 'id'));

        $this->hasOne('marca', array(
             'local' => 'marca_id',
             'foreign' => 'id'));

        $this->hasMany('detalle_solicitud', array(
             'local' => 'id',
             'foreign' => 'articulo_id'));

        $this->hasMany('inventario', array(
             'local' => 'id',
             'foreign' => 'articulo_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}