<?php

/**
 * Basecategoria
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $descripcion
 * @property boolean $activo
 * @property Doctrine_Collection $articulo
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method string              getDescripcion() Returns the current record's "descripcion" value
 * @method boolean             getActivo()      Returns the current record's "activo" value
 * @method Doctrine_Collection getArticulo()    Returns the current record's "articulo" collection
 * @method categoria           setId()          Sets the current record's "id" value
 * @method categoria           setDescripcion() Sets the current record's "descripcion" value
 * @method categoria           setActivo()      Sets the current record's "activo" value
 * @method categoria           setArticulo()    Sets the current record's "articulo" collection
 * 
 * @package    solmed
 * @subpackage model
 * @author     Piero Recchia
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class Basecategoria extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('categoria');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('descripcion', 'string', 80, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 80,
             ));
        $this->hasColumn('activo', 'boolean', null, array(
             'type' => 'boolean',
             ));


        $this->index('IX_categoria_1', array(
             'fields' => 
             array(
              0 => 'descripcion',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('articulo', array(
             'local' => 'id',
             'foreign' => 'categoria_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}