<?php

/**
 * BaseProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $sf_guard_user_id
 * @property string $cedula
 * @property string $nombres
 * @property string $apellidos
 * @property string $email
 * @property integer $departamento_id
 * @property sfGuardUser $User
 * @property departamento $departamento
 * 
 * @method integer      getSfGuardUserId()    Returns the current record's "sf_guard_user_id" value
 * @method string       getCedula()           Returns the current record's "cedula" value
 * @method string       getNombres()          Returns the current record's "nombres" value
 * @method string       getApellidos()        Returns the current record's "apellidos" value
 * @method string       getEmail()            Returns the current record's "email" value
 * @method integer      getDepartamentoId()   Returns the current record's "departamento_id" value
 * @method sfGuardUser  getUser()             Returns the current record's "User" value
 * @method departamento getDepartamento()     Returns the current record's "departamento" value
 * @method Profile      setSfGuardUserId()    Sets the current record's "sf_guard_user_id" value
 * @method Profile      setCedula()           Sets the current record's "cedula" value
 * @method Profile      setNombres()          Sets the current record's "nombres" value
 * @method Profile      setApellidos()        Sets the current record's "apellidos" value
 * @method Profile      setEmail()            Sets the current record's "email" value
 * @method Profile      setDepartamentoId()   Sets the current record's "departamento_id" value
 * @method Profile      setUser()             Sets the current record's "User" value
 * @method Profile      setDepartamento()     Sets the current record's "departamento" value
 * 
 * @package    solmed
 * @subpackage model
 * @author     Piero Recchia
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseProfile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('profile');
        $this->hasColumn('sf_guard_user_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('cedula', 'string', 8, array(
             'type' => 'string',
             'length' => 8,
             ));
        $this->hasColumn('nombres', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('apellidos', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('departamento_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'sf_guard_user_id',
             'foreign' => 'id'));

        $this->hasOne('departamento', array(
             'local' => 'departamento_id',
             'foreign' => 'id'));
    }
}