<?php

/**
 * articulo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    saremo
 * @subpackage model
 * @author     UAH
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class articulo extends Basearticulo
{
    public function  __toString() {
        return $this->getDescripcion().' '.$this->getMarca();
    }

    public function  save(Doctrine_Connection $conn = null) {
        $conn = $conn ? $conn : $this->getTable()->getConnection();
        $conn->beginTransaction();
        try {
            $ret = parent::save($conn);
            $this->updateLuceneIndex();
            $conn->commit();
            return $ret;
        } catch (Exception $e) {
            $conn->rollback();
            throw $e;
        }
    }

    public function  delete(Doctrine_Connection $conn = null) {
        $index = TareaTable::getLuceneIndex();
        $hit = $index->find('pk:'.$this->getId());
        if($hit) {
            $index->delete($hit->id);
        }
        return parent::delete($conn);
    }

    public function updateLuceneIndex() {
        $index = articuloTable::getLuceneIndex();
        $hit = $index->find('pk:'.$this->getId());
        if($hit) {
            $index->delete($hit->id);
        }
        $doc = new Zend_Search_Lucene_Document();
        $doc->addField(Zend_Search_Lucene_Field::unIndexed('pk', $this->getId()));
        $doc->addField(Zend_Search_Lucene_Field::unStored('marca', $this->getMarca(), 'utf-8'));
        $doc->addField(Zend_Search_Lucene_Field::unStored('categoria', $this->getCategoria(), 'utf-8'));
        $doc->addField(Zend_Search_Lucene_Field::unStored('descripcion', $this->getDescripcion(), 'utf-8'));
        $index->addDocument($doc);
        $index->commit();
    }
}
