<?php

/**
 * marca
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    saremo
 * @subpackage model
 * @author     UAH
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class marca extends Basemarca
{
    public function  __toString() {
        return $this->getDescripcion();
    }
}
