<?php

/**
 * solicitud
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    saremo
 * @subpackage model
 * @author     UAH
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class solicitud extends Basesolicitud
{
    public function updateInventario() {
        $detalles = $this->getDetalleSolicitud();
        foreach ($detalles as $detalle) {
            echo $detalle->getArticulo().' Cantidad: '.$detalle->getCantidad();
        }
    }
}
